# -*- coding: utf-8 -*-
"""final modal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U2ZvPhrx2LiXJ0rvL8_-fPbhHNMi4IhZ
"""

https://drive.google.com/file/d/1TYTMdk7a5JWOwFq7-95nUH959w8s5CmW/view?usp=share_link